version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shipping_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shipping_test_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongodb:
    image: mongo:6-jammy
    container_name: shipping_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped