apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  # Kita gunakan NodePort agar bisa diakses langsung dari localhost laptop Anda
  type: NodePort 
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 8080        # Port milik Service K8s
      targetPort: 8080  # Port aplikasi Go di dalam container
      nodePort: 30080   # Port tetap di localhost Anda (bebas antara 30000-32767)