// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/log_event.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/MamangPermen/tracking-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockLogEventRepository is a mock of LogEventRepository interface.
type MockLogEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogEventRepositoryMockRecorder
}

// MockLogEventRepositoryMockRecorder is the mock recorder for MockLogEventRepository.
type MockLogEventRepositoryMockRecorder struct {
	mock *MockLogEventRepository
}

// NewMockLogEventRepository creates a new mock instance.
func NewMockLogEventRepository(ctrl *gomock.Controller) *MockLogEventRepository {
	mock := &MockLogEventRepository{ctrl: ctrl}
	mock.recorder = &MockLogEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEventRepository) EXPECT() *MockLogEventRepositoryMockRecorder {
	return m.recorder
}

// InsertLog mocks base method.
func (m *MockLogEventRepository) InsertLog(log model.TrackingLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLog", log)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLog indicates an expected call of InsertLog.
func (mr *MockLogEventRepositoryMockRecorder) InsertLog(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLog", reflect.TypeOf((*MockLogEventRepository)(nil).InsertLog), log)
}
