// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/tracking.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/MamangPermen/tracking-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockTrackingRepository is a mock of TrackingRepository interface.
type MockTrackingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingRepositoryMockRecorder
}

// MockTrackingRepositoryMockRecorder is the mock recorder for MockTrackingRepository.
type MockTrackingRepositoryMockRecorder struct {
	mock *MockTrackingRepository
}

// NewMockTrackingRepository creates a new mock instance.
func NewMockTrackingRepository(ctrl *gomock.Controller) *MockTrackingRepository {
	mock := &MockTrackingRepository{ctrl: ctrl}
	mock.recorder = &MockTrackingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingRepository) EXPECT() *MockTrackingRepositoryMockRecorder {
	return m.recorder
}

// GetResiHistory mocks base method.
func (m *MockTrackingRepository) GetResiHistory(resiID string) (*model.TrackingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResiHistory", resiID)
	ret0, _ := ret[0].(*model.TrackingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResiHistory indicates an expected call of GetResiHistory.
func (mr *MockTrackingRepositoryMockRecorder) GetResiHistory(resiID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResiHistory", reflect.TypeOf((*MockTrackingRepository)(nil).GetResiHistory), resiID)
}
