// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/inbound_repo.go

// Package mocks adalah package untuk GoMock.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInboundRepository adalah simulasi/database palsu dari interface InboundRepository.
type MockInboundRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInboundRepositoryMockRecorder
}

// MockInboundRepositoryMockRecorder adalah mock recorder untuk MockInboundRepository.
type MockInboundRepositoryMockRecorder struct {
	mock *MockInboundRepository
}

// NewMockInboundRepository membuat instance mock baru.
func NewMockInboundRepository(ctrl *gomock.Controller) *MockInboundRepository {
	mock := &MockInboundRepository{ctrl: ctrl}
	mock.recorder = &MockInboundRepositoryMockRecorder{mock}
	return mock
}

// EXPECT mengembalikan objek yang memungkinkan pemanggil untuk menentukan ekspektasi penggunaan.
func (m *MockInboundRepository) EXPECT() *MockInboundRepositoryMockRecorder {
	return m.recorder
}

// GetItemByResi adalah simulasi fungsi untuk mendapatkan item berdasarkan resi.
func (m *MockInboundRepository) GetItemByResi(resi string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByResi", resi)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByResi menunjukkan ekspektasi pemanggilan fungsi GetItemByResi.
func (mr *MockInboundRepositoryMockRecorder) GetItemByResi(resi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByResi", reflect.TypeOf((*MockInboundRepository)(nil).GetItemByResi), resi)
}

// UpdatePackageMetadata adalah simulasi fungsi untuk mengupdate metadata paket.
func (m *MockInboundRepository) UpdatePackageMetadata(resi string, instructions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePackageMetadata", resi, instructions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePackageMetadata menunjukkan ekspektasi pemanggilan fungsi UpdatePackageMetadata.
func (mr *MockInboundRepositoryMockRecorder) UpdatePackageMetadata(resi, instructions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePackageMetadata", reflect.TypeOf((*MockInboundRepository)(nil).UpdatePackageMetadata), resi, instructions)
}

// UpdateStockStatus adalah simulasi fungsi untuk mengupdate status stok paket.
func (m *MockInboundRepository) UpdateStockStatus(resi, warehouseID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockStatus", resi, warehouseID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStockStatus menunjukkan ekspektasi pemanggilan fungsi UpdateStockStatus.
func (mr *MockInboundRepositoryMockRecorder) UpdateStockStatus(resi, warehouseID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockStatus", reflect.TypeOf((*MockInboundRepository)(nil).UpdateStockStatus), resi, warehouseID, status)
}
