// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/manifest_repo.go

// Package mocks adalah package untuk GoMock.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockManifestRepository adalah simulasi/database palsu dari interface ManifestRepository.
type MockManifestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockManifestRepositoryMockRecorder
}

// MockManifestRepositoryMockRecorder adalah mock recorder untuk MockManifestRepository.
type MockManifestRepositoryMockRecorder struct {
	mock *MockManifestRepository
}

// NewMockManifestRepository membuat instance mock baru.
func NewMockManifestRepository(ctrl *gomock.Controller) *MockManifestRepository {
	mock := &MockManifestRepository{ctrl: ctrl}
	mock.recorder = &MockManifestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT mengembalikan objek yang memungkinkan pemanggil untuk menentukan ekspektasi penggunaan.
func (m *MockManifestRepository) EXPECT() *MockManifestRepositoryMockRecorder {
	return m.recorder
}

// AddPackageToManifest adalah simulasi fungsi untuk menambahkan paket ke manifest.
func (m *MockManifestRepository) AddPackageToManifest(manifestID, resi string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPackageToManifest", manifestID, resi)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPackageToManifest menunjukkan ekspektasi pemanggilan fungsi AddPackageToManifest.
func (mr *MockManifestRepositoryMockRecorder) AddPackageToManifest(manifestID, resi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPackageToManifest", reflect.TypeOf((*MockManifestRepository)(nil).AddPackageToManifest), manifestID, resi)
}

// CreateManifest adalah simulasi fungsi untuk membuat manifest baru.
func (m *MockManifestRepository) CreateManifest(truckID, driverName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManifest", truckID, driverName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManifest menunjukkan ekspektasi pemanggilan fungsi CreateManifest.
func (mr *MockManifestRepositoryMockRecorder) CreateManifest(truckID, driverName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManifest", reflect.TypeOf((*MockManifestRepository)(nil).CreateManifest), truckID, driverName)
}

// GetManifestStatus adalah simulasi fungsi untuk mendapatkan status manifest.
func (m *MockManifestRepository) GetManifestStatus(manifestID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManifestStatus", manifestID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManifestStatus menunjukkan ekspektasi pemanggilan fungsi GetManifestStatus.
func (mr *MockManifestRepositoryMockRecorder) GetManifestStatus(manifestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManifestStatus", reflect.TypeOf((*MockManifestRepository)(nil).GetManifestStatus), manifestID)
}

// UpdateManifestStatus adalah simulasi fungsi untuk memperbarui status manifest.
func (m *MockManifestRepository) UpdateManifestStatus(manifestID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManifestStatus", manifestID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateManifestStatus menunjukkan ekspektasi pemanggilan fungsi UpdateManifestStatus.
func (mr *MockManifestRepositoryMockRecorder) UpdateManifestStatus(manifestID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManifestStatus", reflect.TypeOf((*MockManifestRepository)(nil).UpdateManifestStatus), manifestID, status)
}
