// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/sorting_repo.go

// Package mocks adalah package untuk GoMock.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSortingRepository adalah simulasi/database palsu dari interface SortingRepository.
type MockSortingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSortingRepositoryMockRecorder
}

// MockSortingRepositoryMockRecorder adalah mock recorder untuk MockSortingRepository.
type MockSortingRepositoryMockRecorder struct {
	mock *MockSortingRepository
}

// NewMockSortingRepository membuat instance mock baru.
func NewMockSortingRepository(ctrl *gomock.Controller) *MockSortingRepository {
	mock := &MockSortingRepository{ctrl: ctrl}
	mock.recorder = &MockSortingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT mengembalikan objek yang memungkinkan pemanggil untuk menentukan ekspektasi penggunaan.
func (m *MockSortingRepository) EXPECT() *MockSortingRepositoryMockRecorder {
	return m.recorder
}

// AssignToLane adalah simulasi fungsi untuk menugaskan ke lajur/lane.
func (m *MockSortingRepository) AssignToLane(resi, laneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignToLane", resi, laneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignToLane menunjukkan ekspektasi pemanggilan fungsi AssignToLane.
func (mr *MockSortingRepositoryMockRecorder) AssignToLane(resi, laneID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignToLane", reflect.TypeOf((*MockSortingRepository)(nil).AssignToLane), resi, laneID)
}

// GetPackagesInLane adalah simulasi fungsi untuk mendapatkan daftar paket di dalam lajur/lane.
func (m *MockSortingRepository) GetPackagesInLane(laneID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackagesInLane", laneID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackagesInLane menunjukkan ekspektasi pemanggilan fungsi GetPackagesInLane.
func (mr *MockSortingRepositoryMockRecorder) GetPackagesInLane(laneID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackagesInLane", reflect.TypeOf((*MockSortingRepository)(nil).GetPackagesInLane), laneID)
}
