FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

#copy modul supaya caching bisa jalan
COPY go.mod go.sum ./
RUN go mod download
 
# copy semua source code
COPY . .

RUN go build -o main ./cmd/api/main.go

FROM alpine:3.19
WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]