// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/order.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "order-tariff-service/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderService) CreateOrder(req domain.OrderRequest) (domain.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", req)
	ret0, _ := ret[0].(domain.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceMockRecorder) CreateOrder(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderService)(nil).CreateOrder), req)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// GetCityCode mocks base method.
func (m *MockOrderRepository) GetCityCode(cityName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityCode", cityName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityCode indicates an expected call of GetCityCode.
func (mr *MockOrderRepositoryMockRecorder) GetCityCode(cityName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityCode", reflect.TypeOf((*MockOrderRepository)(nil).GetCityCode), cityName)
}

// GetDistance mocks base method.
func (m *MockOrderRepository) GetDistance(origin, dest domain.Koordinat) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistance", origin, dest)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistance indicates an expected call of GetDistance.
func (mr *MockOrderRepositoryMockRecorder) GetDistance(origin, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistance", reflect.TypeOf((*MockOrderRepository)(nil).GetDistance), origin, dest)
}

// GetPricingFromCache mocks base method.
func (m *MockOrderRepository) GetPricingFromCache(key string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPricingFromCache", key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricingFromCache indicates an expected call of GetPricingFromCache.
func (mr *MockOrderRepositoryMockRecorder) GetPricingFromCache(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricingFromCache", reflect.TypeOf((*MockOrderRepository)(nil).GetPricingFromCache), key)
}

// SaveOrder mocks base method.
func (m *MockOrderRepository) SaveOrder(req domain.OrderRequest, res domain.OrderResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", req, res)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderRepositoryMockRecorder) SaveOrder(req, res interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderRepository)(nil).SaveOrder), req, res)
}
