// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dispatcher/dispatcher.go

package mocks

import (
	"context"
	"reflect"

	"papiton/notification-service/internal/model"

	"github.com/golang/mock/gomock"
)

// ─── MockNotificationProvider ─────────────────────────────────────────────────

// MockNotificationProvider is a mock of NotificationProvider interface
type MockNotificationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationProviderMockRecorder
}

// MockNotificationProviderMockRecorder is the mock recorder
type MockNotificationProviderMockRecorder struct {
	mock *MockNotificationProvider
}

func NewMockNotificationProvider(ctrl *gomock.Controller) *MockNotificationProvider {
	mock := &MockNotificationProvider{ctrl: ctrl}
	mock.recorder = &MockNotificationProviderMockRecorder{mock}
	return mock
}

func (m *MockNotificationProvider) EXPECT() *MockNotificationProviderMockRecorder {
	return m.recorder
}

func (m *MockNotificationProvider) Send(ctx context.Context, msg model.NotificationMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockNotificationProviderMockRecorder) Send(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "Send", reflect.TypeOf((*MockNotificationProvider)(nil).Send), ctx, msg,
	)
}

// ─── MockNotificationRepository ───────────────────────────────────────────────

// MockNotificationRepository is a mock of NotificationRepository interface
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

// MockNotificationRepositoryMockRecorder is the mock recorder
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

func (m *MockNotificationRepository) SaveLog(ctx context.Context, msg model.NotificationMessage, status bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLog", ctx, msg, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockNotificationRepositoryMockRecorder) SaveLog(ctx, msg, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "SaveLog", reflect.TypeOf((*MockNotificationRepository)(nil).SaveLog), ctx, msg, status,
	)
}
