// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/location.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/madgeer/papiton-express/shipping-service/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockLocationRepository is a mock of LocationRepository interface.
type MockLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationRepositoryMockRecorder
}

// MockLocationRepositoryMockRecorder is the mock recorder for MockLocationRepository.
type MockLocationRepositoryMockRecorder struct {
	mock *MockLocationRepository
}

// NewMockLocationRepository creates a new mock instance.
func NewMockLocationRepository(ctrl *gomock.Controller) *MockLocationRepository {
	mock := &MockLocationRepository{ctrl: ctrl}
	mock.recorder = &MockLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationRepository) EXPECT() *MockLocationRepositoryMockRecorder {
	return m.recorder
}

// GetLatestLocation mocks base method.
func (m *MockLocationRepository) GetLatestLocation(ctx context.Context, courierID string) (*domain.CourierLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestLocation", ctx, courierID)
	ret0, _ := ret[0].(*domain.CourierLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestLocation indicates an expected call of GetLatestLocation.
func (mr *MockLocationRepositoryMockRecorder) GetLatestLocation(ctx, courierID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestLocation", reflect.TypeOf((*MockLocationRepository)(nil).GetLatestLocation), ctx, courierID)
}

// UpdateLocation mocks base method.
func (m *MockLocationRepository) UpdateLocation(ctx context.Context, loc *domain.CourierLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockLocationRepositoryMockRecorder) UpdateLocation(ctx, loc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockLocationRepository)(nil).UpdateLocation), ctx, loc)
}
