// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/dispatch.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/madgeer/papiton-express/shipping-service/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockDispatchRepository is a mock of DispatchRepository interface.
type MockDispatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchRepositoryMockRecorder
}

// MockDispatchRepositoryMockRecorder is the mock recorder for MockDispatchRepository.
type MockDispatchRepositoryMockRecorder struct {
	mock *MockDispatchRepository
}

// NewMockDispatchRepository creates a new mock instance.
func NewMockDispatchRepository(ctrl *gomock.Controller) *MockDispatchRepository {
	mock := &MockDispatchRepository{ctrl: ctrl}
	mock.recorder = &MockDispatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchRepository) EXPECT() *MockDispatchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDispatchRepository) Create(ctx context.Context, dispatch *domain.Dispatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dispatch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDispatchRepositoryMockRecorder) Create(ctx, dispatch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDispatchRepository)(nil).Create), ctx, dispatch)
}

// GetByOrderID mocks base method.
func (m *MockDispatchRepository) GetByOrderID(ctx context.Context, orderID string) (*domain.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockDispatchRepositoryMockRecorder) GetByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockDispatchRepository)(nil).GetByOrderID), ctx, orderID)
}

// UpdateStatus mocks base method.
func (m *MockDispatchRepository) UpdateStatus(ctx context.Context, id string, status domain.DispatchStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDispatchRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDispatchRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockDispatchService is a mock of DispatchService interface.
type MockDispatchService struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchServiceMockRecorder
}

// MockDispatchServiceMockRecorder is the mock recorder for MockDispatchService.
type MockDispatchServiceMockRecorder struct {
	mock *MockDispatchService
}

// NewMockDispatchService creates a new mock instance.
func NewMockDispatchService(ctrl *gomock.Controller) *MockDispatchService {
	mock := &MockDispatchService{ctrl: ctrl}
	mock.recorder = &MockDispatchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchService) EXPECT() *MockDispatchServiceMockRecorder {
	return m.recorder
}

// AutoDispatchPickUp mocks base method.
func (m *MockDispatchService) AutoDispatchPickUp(ctx context.Context, orderID, pickupZone string) (*domain.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoDispatchPickUp", ctx, orderID, pickupZone)
	ret0, _ := ret[0].(*domain.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoDispatchPickUp indicates an expected call of AutoDispatchPickUp.
func (mr *MockDispatchServiceMockRecorder) AutoDispatchPickUp(ctx, orderID, pickupZone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoDispatchPickUp", reflect.TypeOf((*MockDispatchService)(nil).AutoDispatchPickUp), ctx, orderID, pickupZone)
}

// ConfirmPickUp mocks base method.
func (m *MockDispatchService) ConfirmPickUp(ctx context.Context, dispatchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPickUp", ctx, dispatchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPickUp indicates an expected call of ConfirmPickUp.
func (mr *MockDispatchServiceMockRecorder) ConfirmPickUp(ctx, dispatchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPickUp", reflect.TypeOf((*MockDispatchService)(nil).ConfirmPickUp), ctx, dispatchID)
}

// UpdateCourierGPS mocks base method.
func (m *MockDispatchService) UpdateCourierGPS(ctx context.Context, courierID string, lat, long float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierGPS", ctx, courierID, lat, long)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourierGPS indicates an expected call of UpdateCourierGPS.
func (mr *MockDispatchServiceMockRecorder) UpdateCourierGPS(ctx, courierID, lat, long interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierGPS", reflect.TypeOf((*MockDispatchService)(nil).UpdateCourierGPS), ctx, courierID, lat, long)
}
