// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/courier.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/madgeer/papiton-express/shipping-service/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailableByZone mocks base method.
func (m *MockCourierRepository) GetAvailableByZone(ctx context.Context, zone string) ([]*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableByZone", ctx, zone)
	ret0, _ := ret[0].([]*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableByZone indicates an expected call of GetAvailableByZone.
func (mr *MockCourierRepositoryMockRecorder) GetAvailableByZone(ctx, zone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableByZone", reflect.TypeOf((*MockCourierRepository)(nil).GetAvailableByZone), ctx, zone)
}

// GetByID mocks base method.
func (m *MockCourierRepository) GetByID(ctx context.Context, id string) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCourierRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCourierRepository)(nil).GetByID), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockCourierRepository) UpdateStatus(ctx context.Context, id string, status domain.CourierStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCourierRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCourierRepository)(nil).UpdateStatus), ctx, id, status)
}
